platform:
  - amd64
image: Visual Studio 2017

environment:
  matrix:
    - PYTHON: "C:\\Miniconda3-x64"

# For debugging uncomment the lines below
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

##  Use conda-build
install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set channel_priority flexible
  - conda config --add channels conda-forge
  - conda config --add channels tpeulen
  - conda config --add channels salilab
  - conda config --add channels defaults
  - conda update -q conda
  - conda install git conda-build anaconda-client numpy conda-verify
  - activate base
  - conda build conda-recipe

# use conda build
test_script:
  - conda install nose coverage chisurf -c local
  - python setup.py build_ext --inplace --force
  - nosetests .\test\

### scripts to run after tests
deploy_script:
  - if not "%APPVEYOR_REPO_BRANCH%" == "master" exit 0
  - anaconda upload C:\Miniconda3-x64\envs\build\conda-bld\win-64\chisurf-*.tar.bz2

build: off

# For debugging uncomment the lines below
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

notifications:
  - provider: Email
    to:
      - thomas.otavio.peulen@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
