platform:
  - amd64
image: Visual Studio 2017

environment:
  matrix:
    - PYTHON: "C:\\Miniconda3-x64"

## For debugging uncomment the lines below
#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

##  Use conda-build
#install:
#  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
#  - conda config --set always_yes yes --set changeps1 no
#  - conda update -q conda
#  - conda config --set channel_priority strict
#  - conda config --add channels conda-forge
#  - conda config --add channels tpeulen
#  - conda install git conda-build anaconda-client
#  - activate base
#  - conda build conda-recipe

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set channel_priority strict
  - conda config --add channels conda-forge
  - conda config --add channels tpeulen
  - conda update -q conda
  - conda info -a
  - conda create -q -n build-environment python=$BUILD_TARGET conda-build anaconda-client jinja2 git nose coverage
  - activate build-environment
  - git fetch --unshallow --tags --force
  - conda build conda-recipe

# use conda build
test_script:
  - conda install --use-local chisurf
  - nosetests .\test\

#### scripts to run after tests
#deploy_script:
#  - if not "%APPVEYOR_REPO_BRANCH%" == "master" exit 0
#  - anaconda upload C:\Miniconda3-x64\envs\build\conda-bld\win-64\chisurf-*.tar.bz2

build: off

## For debugging uncomment the lines below
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

notifications:
  - provider: Email
    to:
      - thomas.otavio.peulen@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: false
