platform:
- amd64

environment:
  matrix:
    - PYTHON: "C:\\Miniconda3-x64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda env create -f environment.yaml
  - activate chisurf
  - python.exe setup.py build_ext --inplace
  - python setup.py install

build: off

test_script:
  - conda install nose coverage
  - ps: cd .\test\
  - nosetests --with-coverage test_*.py

