dist: xenial
language: python
sudo: required
python:
  - "3.7"
addons:
  apt:
    packages:
      - libboost-dev
      - libboost-regex-dev
      - libboost-system-dev
      - libboost-test-dev
      - libglew-dev
      - libicu-dev
      - libpng-dev
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
      - python-pip
      - zlib1g-dev
  homebrew:
    packages:
      - ccache
      - glew
      - sdl2
      - sdl2_image
      - sdl2_mixer
      - sdl2_ttf
    update: true

before_script:
  - >
    if [ "$TRAVIS_DIST" == "trusty" ]; then \
      export DISPLAY=:99.0 && \
      sh -e /etc/init.d/xvfb start && \
      sleep 3; \
    fi

#services:
#  - xvfb
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create -f environment.yaml
  - source activate chisurf
  - python setup.py build_ext --inplace --force
install:
  - python setup.py install
script:
  - source activate chisurf
  - conda install nose coverage
  - ln -sf $(which nosetests) $(pwd)/test/
  - cd $(pwd)/test/
  #- xvfb-run -a nosetests --with-coverage test_*.py
  - nosetests --with-coverage test_*.py
after_success:
  - source activate chisurf
  - pip install codacy-coverage
  - coverage xml
  - python-codacy-coverage -r coverage.xml
#  - conda install conda-build anaconda-client git
#  - git clone https://github.com/Fluorescence-Tools/conda-recipes.git
#  -
