language: python
sudo: required
services:
  - xvfb
python:
  - "3.7"
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create -f environment.yaml
  - source activate chisurf
  - python setup.py build_ext --inplace --force
install:
  - python setup.py install
script:
  - source activate chisurf
  - conda install nose coverage
  - ln -sf $(which nosetests) $(pwd)/test/
  - cd $(pwd)/test/
  - "export DISPLAY=:99.0"
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sh -e /etc/init.d/xvfb start; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok )& fi
  - sleep 3 # give xvfb some time to start
  - nosetests --with-coverage test_*.py  > /dev/null
after_success:
  - source activate chisurf
  - pip install codacy-coverage
  - coverage xml
  - python-codacy-coverage -r coverage.xml
