dist: trusty
language: python
sudo: required
python:
  - "3.7"
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create -f environment.yaml
  - source activate chisurf
  - python setup.py build_ext --inplace --force
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
install:
  - python setup.py install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - source activate chisurf
  - conda install nose coverage
  - ln -sf $(which nosetests) $(pwd)/test/
  - cd $(pwd)/test/
  - xvfb-run --server-args="-screen 0 1280x1024x24" nosetests --with-coverage test_*.py
  #- nosetests --with-coverage test_*.py
after_success:
  - source activate chisurf
  - pip install codacy-coverage
  - coverage xml
  - python-codacy-coverage -r coverage.xml
#  - conda install conda-build anaconda-client git
#  - git clone https://github.com/Fluorescence-Tools/conda-recipes.git
#  -
