language: python
sudo: required

matrix:
  include:
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=2.7
    - os: linux
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.6

addons:
  apt:
    packages:
      - libglew-dev
      - libicu-dev
      - libpng-dev
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
      - zlib1g-dev

services:
  - xvfb

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set channel_priority strict
  - conda config --add channels conda-forge
  - conda config --add channels tpeulen
  - conda update -q conda
  - conda info -a
  - conda install git conda-build anaconda-client jinja2
  - conda init bash
  - conda activate base
  - git pull
  - git fetch --unshallow
  - conda build conda-recipe --output-folder bld-dir
  - conda config --add channels "file://`pwd`/bld-dir"

install:
  - conda install chisurf

script:
  - conda install nose coverage
  - python setup.py build_ext --inplace --force
  - xvfb-run --server-args="-screen 0 1280x1024x24 +extension GLX" -a nosetests --with-coverage test/test_*.py

after_success:
  - OS=$TRAVIS_OS_NAME-64
  - pip install codacy-coverage
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - |
    if [[ "$TRAVIS_BRANCH" == "master" ]];
    then
      anaconda upload bld-dir/**/chisurf*.tar.bz2
    fi
