name: chisurf

channels:
  - tpeulen
  - pytorch
  - conda-forge

dependencies:
    # the version 5.12.3 has an issue in combination with
    # python>=3.7.3. This is supossably resolved in 5.13.1
    # (see: https://github.com/GNS3/gns3-gui/issues/2819)
    - python=3.7.3
    - pyyaml
    - python-slugify
    - numpy
    - numba
    - scipy
    - emcee
    - numexpr
    - pytables
    - mdtraj
    - ipython
    - matplotlib
    - pyqt
    - pyqtgraph
    - qscintilla2
    - pyopengl
    - qtconsole
    - python-docx
    - labellib
    - deprecation
    - pyopencl
    - guiqwt
    - progressbar2
    - qtpy
    - mrcfile
    - htmd-pdb2pqr
    - pymol-open-source
    - tttrlib
    - chinet
    - librttr
    - libmongoc
    - opencv
    - labellib
    - cython
    - nose
