name: chisurf

channels:
  - tpeulen
  - conda-forge
  - defaults

dependencies:
    - python=3.7
    - cython
    - pyyaml
    - python-slugify
    - numpy
    - numba
    - scipy
    - emcee
    - numexpr
    - pytables
    - hdf5
    - mdtraj
    - ipython
    - matplotlib
    - pyqt
    - pyqtgraph
    - qscintilla2
    - pyopengl
    - qtconsole
    - python-docx
    - labellib
    - deprecation
    - pyopencl
    - progressbar2
    - qtpy
    - sphinx
    - htmd-pdb2pqr
    - pymol-open-source
    - mrcfile
    - guiqwt
    - tttrlib
#    - sympy
#    - sphinx_bootstrap_theme
#    - sphinx-autodoc-typehints
#    - numpydoc
