name: chisurf

channels:
  - tpeulen
  - salilab
  - conda-forge
  - defaults

dependencies:
    - python =3.7.3
    - nose
    - imp >=2.12.0
    - pyyaml
    - python-slugify
    - numpy
    - numba
    - numexpr 2.7.*
    - scipy
    - emcee
    - mdtraj
    - ipython
    - qtconsole
    # jupyter_client 6.0.0 causes an error
    # File "C:\Miniconda3\envs\chisurf\lib\site-packages\jupyter_client\client.py", line 200, in control_channel
    # socket, self.session, self.ioloop
    # TypeError: ChannelABC() takes no arguments
    - jupyter_client <6.0.0|>6.0.0
    - matplotlib >=3.1.3
    # the version 5.12.3 has an issue in combination with
    # python>=3.7.3. This is probably resolved in 5.13.1
    # (see: https://github.com/GNS3/gns3-gui/issues/2819)
    - pyqt >=5.13.1|<=5.12.1|>=5.9.0
    - pyqtgraph >0.0.10
    - qscintilla2 >=2.10.8
    - pyopengl
    - python-docx
    - deprecation
    - pyopencl
    - guiqwt >=3.0.0
    - progressbar2
    - qtpy
    - mrcfile
    - htmd-pdb2pqr 0.0.2.*
    - opencv 3.4.1.*
    - cython 0.29.15.*
    - pymol-open-source 2.3.0.*
    - labellib
    - tttrlib >=0.0.12
    - chinet >=0.0.5
