#!/bin/sh
export APP_NAME=ChiSurf
./build-osx-app.sh -f=../../environment.yml -i=../../chisurf/gui/resources/icons/cs_logo.png -n=$APP_NAME -m=chisurf -p=../../ -o=../../dist
test -f ../dist/$APP_NAME-Installer.dmg && rm ../dist/$APP_NAME-Installer.dmg
python generate-iconset.py resources/VolumeIcon.png
./create-dmg/create-dmg \
  --volname "$APP_NAME Installer" \
  --window-pos 200 120 \
  --window-size 800 400 \
  --icon-size 100 \
  --icon "$APP_NAME.app" 200 190 \
  --hide-extension "$APP_NAME.app" \
  --app-drop-link 600 185 \
  --volicon resources/VolumeIcon.icns \
  "../../dist/$APP_NAME-Installer.dmg" \
  "../../dist/"
./fileicon set "../../dist/$APP_NAME-Installer.dmg" ./resources/VolumeIcon.icns
rm -rf ../../dist/$APP_NAME.app
