"""
Dynamically collect all entry points for ChiSurf and patch recipe.yaml.

Discovers entry points from:
1. pyproject.toml [project.scripts] and [project.gui-scripts]
2. chisurf/plugins/*/__init__.py files (cli_entrypoint variable)

Writes entry_points.json for reference and patches recipe.yaml in-place
between the BEGIN_ENTRY_POINTS / END_ENTRY_POINTS sentinel comments.
"""

import sys
import json
import pathlib
import ast
import os
import re

if sys.version_info >= (3, 11):
    import tomllib
else:
    try:
        import tomli as tomllib
    except ImportError:
        print("ERROR: tomli required for Python < 3.11. Install with: pip install tomli")
        sys.exit(1)


def read_pyproject_entry_points(pyproject_path: pathlib.Path):
    """Read entry points from pyproject.toml [project.scripts] and [project.gui-scripts]."""
    scripts = {}
    gui_scripts = {}
    if not pyproject_path.exists():
        return scripts, gui_scripts
    try:
        with open(pyproject_path, "rb") as f:
            pyproject = tomllib.load(f)
    except Exception as e:
        print(f"WARNING: Failed to read {pyproject_path}: {e}")
        return scripts, gui_scripts
    project = pyproject.get("project", {})
    for name, func in project.get("scripts", {}).items():
        scripts[name] = func
    for name, func in project.get("gui-scripts", {}).items():
        gui_scripts[name] = func
    return scripts, gui_scripts


def read_plugin_cli_entrypoint(init_py: pathlib.Path):
    """AST-parse a plugin __init__.py for cli_entrypoint = '...' assignment."""
    if not init_py.exists():
        return None
    try:
        source = init_py.read_text(encoding="utf-8")
        tree = ast.parse(source, filename=str(init_py))
    except Exception:
        return None
    for node in ast.walk(tree):
        if not isinstance(node, ast.Assign):
            continue
        for target in getattr(node, "targets", []):
            if isinstance(target, ast.Name) and target.id == "cli_entrypoint":
                v = node.value
                if isinstance(v, ast.Constant) and isinstance(v.value, str):
                    return v.value.strip()
    return None


def discover_plugin_entry_points(plugins_dir: pathlib.Path) -> dict:
    """Walk plugins directory collecting cli_entrypoint from each __init__.py."""
    scripts = {}
    if not plugins_dir.exists() or not plugins_dir.is_dir():
        return scripts
    for root, dirs, files in os.walk(str(plugins_dir)):
        if "__init__.py" not in files:
            continue
        ep = read_plugin_cli_entrypoint(pathlib.Path(root) / "__init__.py")
        if ep:
            # Entry point string is "name = module:func"
            if "=" in ep:
                name, func = ep.split("=", 1)
                scripts[name.strip()] = func.strip()
            else:
                # Fallback: if it's just a module? No, entry points should have =
                pass
    return scripts


def patch_recipe(recipe_path: pathlib.Path, scripts: dict, gui_scripts: dict) -> None:
    """
    Replace the entry_points list in recipe.yaml between sentinel comments.
    """
    # Read as binary to detect line endings, then decode with universal newlines
    raw = recipe_path.read_bytes()
    crlf = b"\r\n" in raw
    text = raw.decode("utf-8").replace("\r\n", "\n")

    # Build the replacement block (indented to match recipe style: 6 spaces)
    indent = "      "
    lines = [f"{indent}# BEGIN_ENTRY_POINTS (auto-generated by collect_entry_points.py - do not edit manually)"]
    
    # Merge for recipe (it doesn't care about type)
    all_eps = []
    for name, func in scripts.items():
        all_eps.append(f"{name} = {func}")
    for name, func in gui_scripts.items():
        all_eps.append(f"{name} = {func}")

    for ep in all_eps:
        lines.append(f"{indent}- {ep}")
    lines.append(f"{indent}# END_ENTRY_POINTS")
    replacement = "\n".join(lines)

    pattern = r"[ \t]*#\s*BEGIN_ENTRY_POINTS.*?[ \t]*#\s*END_ENTRY_POINTS"
    m = re.search(pattern, text, flags=re.DOTALL)
    if not m:
        print(f"WARNING: sentinel comments not found in {recipe_path}; recipe not patched.")
        return

    new_text = re.sub(
        pattern,
        replacement,
        text,
        flags=re.DOTALL,
    )

    if new_text != text:
        out = new_text.replace("\n", "\r\n") if crlf else new_text
        recipe_path.write_bytes(out.encode("utf-8"))
        print(f"Patched {recipe_path} with {len(all_eps)} entry points")
    else:
        print(f"No changes needed for {recipe_path}")


def main():
    script_dir = pathlib.Path(__file__).resolve().parent
    project_root = script_dir.parent

    pyproject_path = project_root / "pyproject.toml"
    plugins_dir = project_root / "chisurf" / "plugins"
    json_path = script_dir / "entry_points.json"
    recipe_path = script_dir / "recipe.yaml"

    static_scripts, static_gui = read_pyproject_entry_points(pyproject_path)
    plugin_scripts = discover_plugin_entry_points(plugins_dir)
    
    scripts = {**static_scripts, **plugin_scripts}
    gui_scripts = static_gui

    # Write JSON with categorization
    data = {
        "console_scripts": scripts,
        "gui_scripts": gui_scripts
    }
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
    print(f"Generated {json_path} with {len(scripts)} console and {len(gui_scripts)} gui scripts")

    # Patch recipe.yaml in-place
    patch_recipe(recipe_path, scripts, gui_scripts)

    if "--print" in sys.argv:
        print("Console Scripts:")
        for name, func in scripts.items():
            print(f"  {name} = {func}")
        print("GUI Scripts:")
        for name, func in gui_scripts.items():
            print(f"  {name} = {func}")



if __name__ == "__main__":
    main()
