"""
Dynamically collect all entry points for ChiSurf and patch recipe.yaml.

Discovers entry points from:
1. pyproject.toml [project.scripts] and [project.gui-scripts]
2. chisurf/plugins/*/__init__.py files (cli_entrypoint variable)

Writes entry_points.json for reference and patches recipe.yaml in-place
between the BEGIN_ENTRY_POINTS / END_ENTRY_POINTS sentinel comments.
"""

import sys
import json
import pathlib
import ast
import os
import re

if sys.version_info >= (3, 11):
    import tomllib
else:
    try:
        import tomli as tomllib
    except ImportError:
        print("ERROR: tomli required for Python < 3.11. Install with: pip install tomli")
        sys.exit(1)


def read_pyproject_entry_points(pyproject_path: pathlib.Path) -> list:
    """Read entry points from pyproject.toml [project.scripts] and [project.gui-scripts]."""
    entry_points = []
    if not pyproject_path.exists():
        return entry_points
    try:
        with open(pyproject_path, "rb") as f:
            pyproject = tomllib.load(f)
    except Exception as e:
        print(f"WARNING: Failed to read {pyproject_path}: {e}")
        return entry_points
    project = pyproject.get("project", {})
    for name, func in project.get("scripts", {}).items():
        entry_points.append(f"{name} = {func}")
    for name, func in project.get("gui-scripts", {}).items():
        entry_points.append(f"{name} = {func}")
    return entry_points


def read_plugin_cli_entrypoint(init_py: pathlib.Path):
    """AST-parse a plugin __init__.py for cli_entrypoint = '...' assignment."""
    if not init_py.exists():
        return None
    try:
        source = init_py.read_text(encoding="utf-8")
        tree = ast.parse(source, filename=str(init_py))
    except Exception:
        return None
    for node in ast.walk(tree):
        if not isinstance(node, ast.Assign):
            continue
        for target in getattr(node, "targets", []):
            if isinstance(target, ast.Name) and target.id == "cli_entrypoint":
                v = node.value
                if isinstance(v, ast.Constant) and isinstance(v.value, str):
                    return v.value.strip()
                if hasattr(ast, "Str") and isinstance(v, ast.Str):
                    return v.s.strip()
    return None


def discover_plugin_entry_points(plugins_dir: pathlib.Path) -> list:
    """Walk plugins directory collecting cli_entrypoint from each __init__.py."""
    entry_points = []
    if not plugins_dir.exists() or not plugins_dir.is_dir():
        return entry_points
    for root, dirs, files in os.walk(str(plugins_dir)):
        if "__init__.py" not in files:
            continue
        ep = read_plugin_cli_entrypoint(pathlib.Path(root) / "__init__.py")
        if ep:
            entry_points.append(ep)
    return entry_points


def patch_recipe(recipe_path: pathlib.Path, entry_points: list) -> None:
    """
    Replace the entry_points list in recipe.yaml between sentinel comments.

    The recipe must contain exactly:
        # BEGIN_ENTRY_POINTS (auto-generated ...)
        ...old lines...
        # END_ENTRY_POINTS
    """
    # Read as binary to detect line endings, then decode with universal newlines
    raw = recipe_path.read_bytes()
    crlf = b"\r\n" in raw
    text = raw.decode("utf-8").replace("\r\n", "\n")

    # Build the replacement block (indented to match recipe style: 6 spaces)
    indent = "      "
    lines = [f"{indent}# BEGIN_ENTRY_POINTS (auto-generated by collect_entry_points.py - do not edit manually)"]
    for ep in entry_points:
        lines.append(f"{indent}- {ep}")
    lines.append(f"{indent}# END_ENTRY_POINTS")
    replacement = "\n".join(lines)

    # Simpler regex that just looks for the sentinels regardless of exact spacing
    pattern = r"[ \t]*#\s*BEGIN_ENTRY_POINTS.*?[ \t]*#\s*END_ENTRY_POINTS"
    m = re.search(pattern, text, flags=re.DOTALL)
    if not m:
        print(f"WARNING: sentinel comments not found in {recipe_path}; recipe not patched.")
        return

    new_text = re.sub(
        pattern,
        replacement,
        text,
        flags=re.DOTALL,
    )

    if new_text != text:
        # Restore original line endings
        out = new_text.replace("\n", "\r\n") if crlf else new_text
        recipe_path.write_bytes(out.encode("utf-8"))
        print(f"Patched {recipe_path} with {len(entry_points)} entry points")
    else:
        print(f"No changes needed for {recipe_path}")


def main():
    script_dir = pathlib.Path(__file__).resolve().parent
    project_root = script_dir.parent

    pyproject_path = project_root / "pyproject.toml"
    plugins_dir = project_root / "chisurf" / "plugins"
    json_path = script_dir / "entry_points.json"
    recipe_path = script_dir / "recipe.yaml"

    static_eps = read_pyproject_entry_points(pyproject_path)
    plugin_eps = discover_plugin_entry_points(plugins_dir)
    all_eps = static_eps + plugin_eps

    # Write JSON (for reference / other consumers)
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump({"entry_points": all_eps}, f, indent=2)
    print(f"Generated {json_path} with {len(all_eps)} entry points")

    # Patch recipe.yaml in-place
    patch_recipe(recipe_path, all_eps)

    if "--print" in sys.argv:
        for ep in all_eps:
            print(f"  {ep}")


if __name__ == "__main__":
    main()
