@echo off
setlocal enabledelayedexpansion

:: ---------------------------------------------------------------------------
:: build-setup.bat
::
:: Builds the ChiSurf package (via rattler-build) and then creates a
:: self-contained Windows installer (via Inno Setup).
::
:: Prerequisites (all handled through pixi -e build):
::   - rattler-build, rattler-index, micromamba  (in pixi build env)
::   - Inno Setup 6 at "C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
::   - MSVC build tools for Cython/CMake extensions
::
:: Usage (from project root):
::   pixi run -e build build-setup
::
:: Or directly (requires pixi in PATH and build env installed):
::   cd build_tools\win
::   build-setup.bat [/nobuild] [--output-dir <path>]
::
:: Flags:
::   /nobuild       Skip package build (use existing packages)
::   --output-dir   Override output directory for packages
:: ---------------------------------------------------------------------------

:: Resolve script and project root paths
set "SCRIPT_DIR=%~dp0"
:: Remove trailing backslash from SCRIPT_DIR
if "%SCRIPT_DIR:~-1%"=="\" set "SCRIPT_DIR=%SCRIPT_DIR:~0,-1%"

:: Project root is two levels up from build_tools\win
pushd "%SCRIPT_DIR%\..\.."
set "SOURCE_PATH=%CD%"
popd

set "DIST_PATH=%SOURCE_PATH%\dist"
set "APP_PATH=%DIST_PATH%\win"
set "RATTLER_RECIPE_FOLDER=%SOURCE_PATH%\rattler-recipe"
set "OUTPUT_DIR=%SOURCE_PATH%\conda-bld"
set "PIXI_MANIFEST=%SOURCE_PATH%\pixi.toml"

:: Default: build the package
set "BUILD_RATTLER_PACKAGE=1"

:: Parse command-line arguments
:parse_args
if "%~1"=="" goto done_args
if /I "%~1"=="/nobuild" (
    set "BUILD_RATTLER_PACKAGE=0"
    shift
    goto parse_args
)
if /I "%~1"=="--output-dir" (
    set "OUTPUT_DIR=%~2"
    shift
    shift
    goto parse_args
)
shift
goto parse_args
:done_args

:: Normalize to absolute paths
for %%I in ("%DIST_PATH%")             do set "DIST_PATH=%%~fI"
for %%I in ("%APP_PATH%")              do set "APP_PATH=%%~fI"
for %%I in ("%SOURCE_PATH%")           do set "SOURCE_PATH=%%~fI"
for %%I in ("%RATTLER_RECIPE_FOLDER%") do set "RATTLER_RECIPE_FOLDER=%%~fI"
for %%I in ("%OUTPUT_DIR%")            do set "OUTPUT_DIR=%%~fI"
for %%I in ("%PIXI_MANIFEST%")         do set "PIXI_MANIFEST=%%~fI"

echo.
echo === ChiSurf Windows Build ===
echo SCRIPT_DIR        = %SCRIPT_DIR%
echo SOURCE_PATH       = %SOURCE_PATH%
echo DIST_PATH         = %DIST_PATH%
echo APP_PATH          = %APP_PATH%
echo RATTLER_RECIPE    = %RATTLER_RECIPE_FOLDER%
echo OUTPUT_DIR        = %OUTPUT_DIR%
echo PIXI_MANIFEST     = %PIXI_MANIFEST%
echo.

if defined INNO_SETUP_EXE goto InnoCheck
if exist "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" set "INNO_SETUP_EXE=C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
if exist "C:\Program Files\Inno Setup 6\ISCC.exe" set "INNO_SETUP_EXE=C:\Program Files\Inno Setup 6\ISCC.exe"
:InnoCheck
if not defined INNO_SETUP_EXE (
    echo ERROR: Inno Setup compiler not found. Set INNO_SETUP_EXE or install Inno Setup 6.
    exit /b 1
)

:: -----------------------------------------------------------------------
:: Compute version (PEP 440 compatible) if not already set in environment
:: -----------------------------------------------------------------------
if not "%CHISURF_VERSION%"=="" goto SkipVersion
for /f "delims=" %%v in ('python "%SOURCE_PATH%\rattler-recipe\generate_version.py" --print') do set "CHISURF_VERSION=%%v"
if "%CHISURF_VERSION%"=="" (
    echo ERROR: Failed to generate version using generate_version.py
    exit /b 1
)
:SkipVersion
echo CHISURF_VERSION = %CHISURF_VERSION%

:: Write version.json for rattler-build to load
echo {"version": "%CHISURF_VERSION%"} > "%RATTLER_RECIPE_FOLDER%\version.json"

:: -----------------------------------------------------------------------
:: entry_points.json is already generated by the pixi task dependency
:: (collect-entry-points runs before build-setup via depends-on).
:: Verify it exists; if not (direct bat invocation), generate it now.
:: -----------------------------------------------------------------------
if not exist "%RATTLER_RECIPE_FOLDER%\entry_points.json" (
    echo Generating entry_points.json ...
    python "%RATTLER_RECIPE_FOLDER%\collect_entry_points.py"
    if errorlevel 1 (
        echo ERROR: Failed to collect entry points
        exit /b 1
    )
)

:: ---------------------------------------------------------------------------
:: Ensure micromamba is on PATH (installed by CI or locally)
:: ---------------------------------------------------------------------------
where micromamba >nul 2>nul
if errorlevel 1 (
    echo ERROR: micromamba not found. Install via 'micromamba shell init' or CI setup.
    exit /b 1
)

:: -----------------------------------------------------------------------
:: Build package via rattler-build
:: -----------------------------------------------------------------------
if "%BUILD_RATTLER_PACKAGE%"=="1" (
    echo [1/3] Building package ...
    rattler-build build --recipe "%RATTLER_RECIPE_FOLDER%" --output-dir "%OUTPUT_DIR%" --test skip
) else (
    echo [1/3] Skipping package build ^(/nobuild^)
)

:: -----------------------------------------------------------------------
:: Create the distribution environment from the local package
:: -----------------------------------------------------------------------
echo.
echo [2/3] Creating distribution environment at %APP_PATH% ...

if not exist "%DIST_PATH%" mkdir "%DIST_PATH%"
if exist "%APP_PATH%" (
    echo Removing existing environment ...
    rmdir /s /q "%APP_PATH%"
)

:: Find the built conda package
set "CHISURF_PKG="
for %%f in ("%OUTPUT_DIR%\win-64\chisurf-*.conda") do set "CHISURF_PKG=%%f"
if not defined CHISURF_PKG (
    echo ERROR: No chisurf conda package found in %OUTPUT_DIR%\win-64
    exit /b 1
)
echo Found package: %CHISURF_PKG%

set "CHISURF_PKG_URL=%CHISURF_PKG:\=/%"
micromamba create -y ^
    --prefix "%APP_PATH%" ^
    python ^
    chisurf ^
    jinja2 ^
    "file:///%CHISURF_PKG_URL%" ^
    -c conda-forge ^
    --no-channel-priority
if errorlevel 1 (
    echo ERROR: micromamba create failed
    exit /b 1
)

set "PYTHON_EXE="
if exist "%APP_PATH%\python.exe" set "PYTHON_EXE=%APP_PATH%\python.exe"
if not defined PYTHON_EXE if exist "%APP_PATH%\Scripts\python.exe" set "PYTHON_EXE=%APP_PATH%\Scripts\python.exe"
if not defined PYTHON_EXE (
    echo ERROR: python.exe not found in %APP_PATH%
    exit /b 1
)

echo Installing tttrlib via pip (Windows) ...
if exist "%APP_PATH%\Scripts\pip.exe" (
    call "%APP_PATH%\Scripts\pip.exe" install tttrlib --no-cache-dir
) else (
    call "%PYTHON_EXE%" -m pip install tttrlib --no-cache-dir
)
if errorlevel 1 (
    echo WARNING: Could not install tttrlib
)

echo Verifying chisurf installation ...
"%PYTHON_EXE%" -c "import sys; sys.path.insert(0, r'%APP_PATH%\Lib\site-packages'); import chisurf; print('chisurf OK:', chisurf.__version__)"
if errorlevel 1 (
    echo WARNING: Could not verify chisurf import (may be OK in sandboxed environment)
)

:: Pre-compile Python files
echo Compiling .pyc files ...
"%PYTHON_EXE%" -m compileall -qq "%APP_PATH%"

:: Strip dev-only bloat
echo Stripping headers, docs, .lib files ...
if exist "%APP_PATH%\include"              rmdir /s /q "%APP_PATH%\include"
if exist "%APP_PATH%\Library\share\doc"   rmdir /s /q "%APP_PATH%\Library\share\doc"
if exist "%APP_PATH%\Library\share\IMP"   rmdir /s /q "%APP_PATH%\Library\share\IMP"
if exist "%APP_PATH%\Library\include"     rmdir /s /q "%APP_PATH%\Library\include"
if exist "%APP_PATH%\etc\conda\test-files" rmdir /s /q "%APP_PATH%\etc\conda\test-files"
for /r "%APP_PATH%\Library\lib" %%F in (*.lib) do del /q "%%F"

:: -----------------------------------------------------------------------
:: Generate Inno Setup script and build setup.exe
:: -----------------------------------------------------------------------
echo.
echo [3/3] Building Windows installer ...

:: create_installer_script.py must run from the build_tools\win directory
cd /d "%SCRIPT_DIR%"
call "%PYTHON_EXE%" create_installer_script.py
if errorlevel 1 (
    echo ERROR: Failed to generate Inno Setup script
    exit /b 1
)

if not defined INNO_SETUP_EXE (
    echo ERROR: INNO_SETUP_EXE is not set.
    exit /b 1
)
"%INNO_SETUP_EXE%" installer_config.iss
if errorlevel 1 (
    echo ERROR: Inno Setup failed
    exit /b 1
)

if exist installer_config.iss del /q installer_config.iss

:: -----------------------------------------------------------------------
:: Report version and clean up
:: -----------------------------------------------------------------------
set "CHISURF_VERSION_BUILT=%CHISURF_VERSION%"
echo.
echo === Build complete ===
echo Version: %CHISURF_VERSION_BUILT%
echo Installer: %DIST_PATH%\chisurf_windows_setup_%CHISURF_VERSION_BUILT%.exe

:: Remove the staging environment (the installer bundles it)
echo Removing staging environment ...
rmdir /s /q "%APP_PATH%"

cd /d "%SOURCE_PATH%"
echo Done.
exit /b 0
