name: chisurf
version: 2020.03.26
summary: Fluorescence data analysis tool
description: |
  ChiSurf is a software package for the analysis of complex fluorescence
  data acquired in time-resolved single-molecule and ensemble fluorescence
  experiments. The main feature of ChiSurf is the joint (global) analysis of
  multiple datasets.
confinement: strict
base: core18

parts:
  ipython:
    plugin: conda
    conda-miniconda-version: 4.6.14
    conda-packages:
      - ipython
    conda-python-version: "3.7"
#  chisurf:
#    plugin: python
#    python-version: python3
#    source: "."
#    source-type: local
#    stage-packages:
#      - python3.7-minimal
#      - libboost-system1.65.1
#      - libboost-date-time1.65.1
#      - libgomp1
#  qt5:
#    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
#    source-subdir: qt
#    plugin: make
#    make-parameters: ["FLAVOR=qt5"]
#    build-packages:
#      - qtbase5-dev
#      - dpkg-dev
#    stage-packages:
#      - libxkbcommon0
#      - ttf-ubuntu-font-family
#      - dmz-cursor-theme
#      - light-themes
#      - adwaita-icon-theme
#      - gnome-themes-standard
#      - shared-mime-info
#      - libqt5gui5
#      - libgdk-pixbuf2.0-0
#      - libqt5svg5 # for loading icon themes which are svg
#      - try: [appmenu-qt5] # not available on core18
#      - locales-all
#  desktop-qt5:
#    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
#    source-subdir: qt
#    plugin: make
#    make-parameters: ["FLAVOR=qt5"]
#    build-packages:
#      - build-essential
#      - qtbase5-dev
#      - dpkg-dev
#    stage-packages:
#      - libxkbcommon0
#      - ttf-ubuntu-font-family
#      - dmz-cursor-theme
#      - light-themes
#      - gnome-themes-standard
#      - shared-mime-info
#      - libqt5gui5
#      - libgdk-pixbuf2.0-0
#      - libqt5svg5 # for loading icon themes which are svg
#      - try: [appmenu-qt5] # not available on core18
#      - locales-all
#      - xdg-user-dirs
#      - fcitx-frontend-qt5

architectures:
  - build-on: amd64
    run-on: amd64

apps:
  chisurf:
    command: desktop-launch ${SNAP}/Olga
    plugs:
      - home
      - unity7
      - x11
      - opengl
      - pulseaudio
      - wayland
      - network
      - desktop
      - desktop-legacy

grade: stable
