{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.get('name')|lower }}
  version: {{ data.get('version')|lower }}

source:
  path: ..

build:
  number: 0
  binary_relocation: True  # Relocate binaries correctly (for shared libraries, etc.).
  detect_binary_files_with_prefix: True  # [not win]
  entry_points:
    {% for entry_point_type, entry_points in data.get("entry_points", dict()).items() -%}
    {% for entry_point in entry_points -%}
    - {{ entry_point }}
    {% endfor %}
    {% endfor %}

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - swig <4.3.0
    - cmake-build-extension
    - pkg-config   # [not win]
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - pip
    - cmake
    - make         # [linux]
    - ninja
    - swig <4.3.0
    - tttrlib
    - pkg-config   # [not win]
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - python
    - typing_extensions <=4.5
    - pip
    - cython <3.0
    - pyopencl
    - pocl >=0.14      # [linux or osx]
    - oclgrind          # [win]
    - guidata
    - guiqwt
    - pyyaml
    - numpy
    - pyqt           # Needed for pyrcc5 (updating PyQt resource files)
    # Needed for chinet
    - libmongoc
    - doxygen
    - boost-cpp 1.84.*
    - numpy
  run:
    - python
    - numpy
    - pyyaml
    - python-slugify
    - pyqtgraph >=0.13
    - matplotlib
    - deprecation
    - imp
    - pandas <=2.1
    - typing-extensions 4.5.*
    - typing_extensions 4.5.*
    - scipy 1.11.*
    - numba 0.57.*
    - boost-cpp 1.84.*
    - tttrlib >=0.25
    - mdtraj
    - htmd-pdb2pqr
    - ipython 7.*.*
    - notebook
    - pyopencl 2023.*
    - pytools 2023.*
    - emcee 3.1.*
    - pyopengl 3.1.*
    - pytables 3.8.*
    - pocl  >=0.14      # [linux or osx]
    - oclgrind          # [win]
    - pymol-open-source 2.5.*
    - qscintilla2
    - guidata
    - guiqwt
    - qscintilla2
    - python-docx 1.0.*
    - qtconsole 5.*
    - pyqtwebengine
    - ipyfilechooser
    - libcxx
    - joblib

app:
  entry: chisurf
  summary: ChiSurf analysis platform for fluorescence data

test:
  imports:
    - chisurf
  commands:
    - chisurf &        # [linux or osx]

about:
  home: https://github.com/Fluorescence-Tools/ChiSurf
  license: {{ data.get('license') }}
  license_file: LICENSE
  summary: |
    {{ data.get('description') }}
  description: |
    {{ data.get('description') }}

extra:
  recipe-maintainers:
    - tpeulen
