{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.get('name')|lower }}
  version: {{ data.get('version')|lower }}

source:
  path: ..

build:
  number: 0
  binary_relocation: True  # Relocate binaries correctly (for shared libraries, etc.).
  detect_binary_files_with_prefix: True  # [not win]
  entry_points:
    {% for entry_point_type, entry_points in data.get("entry_points", dict()).items() -%}
    {% for entry_point in entry_points -%}
    - {{ entry_point }}
    {% endfor %}
    {% endfor %}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake <4
    - ninja
    - make # [not win]
  host:
    - git
    - swig <4.3.0
    - pkg-config   # [not win]
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - pip
    - python =3.10
    - numpy
    - tttrlib      # [not win]
    - hdf5         # [win]
    - pkg-config   # [not win]
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - typing_extensions 4.5.*
    - pip
    - cython <3.0
    - pyopencl
    - pocl >=0.14      # [linux or osx]
    - oclgrind          # [win]
    - guidata
    - guiqwt
    - pyyaml
    - numpy
    - pyqt           # Needed for pyrcc5 (updating PyQt resource files)
    # Needed for chinet
    - libmongoc
    - doxygen
    - boost-cpp
    - numpy
    - libcxx  # [osx]
    - icu >=75
  run:
    - python =3.10
    - numpy
    - icu >=75
    - pyqt
    - pyyaml
    - click <8.0 # Conflicts with papermill
    - python-slugify
    - pyqtgraph
    - matplotlib
    - scikit-image
    - deprecation
    - imp
    - pandas
    - papermill
    - typing-extensions 4.5.*
    - typing_extensions 4.5.*
    - pytools 2023.*
    - pytables <3.10
    - scipy
    - numba
    - boost-cpp
    - tttrlib >=0.26      # [not win]
    - hdf5                # [win]
    - mdtraj
    - htmd-pdb2pqr
    - ipython <8.0
    - qtconsole 5.*
    - notebook
    - pyopencl
    - emcee 3.1.*
    - pyopengl
    - pocl  >=0.14      # [linux or osx]
    - pymol-open-source
    - qscintilla2
    - guidata
    - guiqwt
    - python-docx
    - pyqtwebengine
    - joblib
    - libcxx  # [osx]
    - hmmlearn

app:
  entry: chisurf
  summary: ChiSurf analysis platform for fluorescence data

test:
  imports:
    - chisurf
  commands:
    - chisurf &        # [linux or osx]

about:
  home: https://github.com/Fluorescence-Tools/ChiSurf
  license: {{ data.get('license') }}
  license_file: LICENSE
  summary: |
    {{ data.get('description') }}
  description: |
    {{ data.get('description') }}

extra:
  recipe-maintainers:
    - tpeulen
