{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set PY_VER_MAJOR = PY_VER[0] %}
{% set PY_VER_MINOR = PY_VER[2] %}


package:
  name: {{ data.get('name')|lower }}
  version: {{ data.get('version')|lower }}

source:
#  path: ..
  git_url: ..

build:
  number: 0
  string: py{{ PY_VER_MAJOR }}{{ PY_VER_MINOR }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  entry_points:
    {% for entry_point_type, entry_points in data.get("entry_points", dict()).items() -%}
    {% for entry_point in entry_points -%}
    - {{ entry_point }}
    {% endfor %}
    {% endfor %}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python {{ python }}
    - setuptools
    - numpy
    - typing_extensions
    - cython
    - pyyaml
    # Needed for pyrcc5 (updated pyqt resource file)
    - pyqt
  host:
    - python {{ python }}
    - setuptools
    - numpy
    - typing_extensions
    - pyyaml
    - cython
  run:
    # There is an issue in versions >= 3.7.3
    # https://www.riverbankcomputing.com/pipermail/pyqt/2019-August/042003.html
    # https://github.com/conda/conda-build/issues/2571
    - python {{ python }}
    - numpy
    - pyyaml >=5.0.0
    - qtpy
    - pyqt
    - pyqtgraph >0.10.0|0.9.10
    - typing_extensions
    - matplotlib >=3.0.0
    - scikit-fluorescence
    - deprecation
    - progressbar2
    - python-slugify
    - cython
    - numexpr
    - numba
    - scipy
    - emcee
    - mdtraj 1.9.*
    - ipython
    - qtconsole
    - jupyter_client 5.3.4.*
    - qscintilla2
    - guiqwt
    - guidata
    - pymol-open-source
    - pyopengl
    - pyopencl
    - python-docx
    - htmd-pdb2pqr
    - opencv
    - mrcfile
    - chinet
    - ndxplorer
    - clsmview
    - k2dist
    - tttrconvert

about:
  home: https://github.com/Fluorescence-Tools/ChiSurf
  license: {{ data.get('license') }}
  license_file: LICENSE
  summary:
    {{ data.get('description') }}
  description: |
    {{ data.get('description') }}

extra:
  recipe-maintainers:
    - tpeulen
