{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.get('name')|lower }}
  version: {{ data.get('version')|lower }}

source:
  path: ..

build:
  number: 0
  skip: true  # [py310]
  entry_points:
    {% for entry_point_type, entry_points in data.get("entry_points", dict()).items() -%}
    {% for entry_point in entry_points -%}
    - {{ entry_point }}
    {% endfor %}
    {% endfor %}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - setuptools
    - pyopencl
    - pocl >=0.14      # [linux or osx]
    - oclgrind          # [win]
    - typing_extensions <=4.5
    - cython
    - pyyaml
    - numpy
    # Needed for pyrcc5 (updated pyqt resource file)
    - pyqt
    - pyqtwebengine
  host:
    - python
    - setuptools
    - cython
    - pyopencl
    - pocl >=0.14      # [linux or osx]
    - oclgrind          # [win]
    - typing_extensions <=4.5
    - pyyaml
    - numpy
    # Needed for pyrcc5 (updated pyqt resource file)
    - pyqt
  run:
    - python
    - {{ pin_compatible('numpy', max_pin='x.x') }}
    - pyyaml
    - pyqtgraph >=0.13
    - matplotlib
    - deprecation
    - scikit-fluorescence
    - imp
    - typing_extensions 4.5.*
    - typing_utils 0.1.*
    - scipy 1.11.*
    - numba 0.57.*
    - tttrlib
    - mdtraj
    - pdb2pqr 3.2.*
    - propka 3.4.*
    - ipython 7.*.*
    - labellib
    - pyopencl 2023.*
    - pytools 2023.*
    - emcee 3.1.*
    - pyopengl 3.1.*
    - pocl  >=0.14      # [linux or osx]
    - oclgrind          # [win]
    - pymol-open-source 2.5.*
    - qscintilla2
    - python-docx 1.0.*
    - qtconsole 5.*
    - chinet >=0.0.8
    - tttrconvert
    - k2dist
    - ndxplorer
    - clsmview
    - pyqtwebengine

app:
  entry: chisurf
  summary: ChiSurf analysis platform for fluorescence data

test:
  imports:
    - chisurf
  commands:
    - chisurf &        # [linux or osx]

about:
  home: https://github.com/Fluorescence-Tools/ChiSurf
  license: {{ data.get('license') }}
  license_file: LICENSE
  summary: |
    {{ data.get('description') }}
  description: |
    {{ data.get('description') }}

extra:
  recipe-maintainers:
    - tpeulen
