{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set name = "chisurf" %}
{% set version = (environ.get("CHISURF_VERSION") or data.get("version") or "0.0.0") %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  binary_relocation: true
  detect_binary_files_with_prefix: true  # [not win]
  entry_points:
    {% for entry_point_type, entry_points in data.get("entry_points", dict()).items() -%}
    {% for entry_point in entry_points -%}
    - {{ entry_point }}
    {% endfor %}
    {% endfor %}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake <4
    - ninja
    - make  # [not win]

  host:
    - python
    - git
    - pip
    - cython >=0.29,<3
    - numpy
    - swig <4.3.0
    - pkg-config  # [not win]
    - llvm-openmp  # [osx]
    - libcxx       # [osx]
    - libgomp      # [linux]
    - doxygen
    - boost-cpp
    - pyqt             # provides pyrcc5 for resource build
    - pybind11
    - eigen

    # Windows-only: if you rely on system tttrlib there, keep hdf5 here
    - hdf5  # [win]

  run:
    - python
    - numpy
    - typing-extensions >=4.14
    - pytools >=2024.0
    - pyyaml
    - click
    - click-didyoumean
    - qtpy
    - pyqt
    - pyqtgraph
    - matplotlib
    - scikit-image
    - deprecation
    - imp
    - pandas
    - scipy
    - numba
    - boost-cpp
    - mdtraj
    - ipython
    - notebook
    - emcee
    - pyopengl
    - pytables
    - pymol-open-source
    - guidata
    - guiqwt
    - python-docx
    - qtconsole
    - pyqtwebengine
    - hmmlearn
    - sympy
    - zeus-mcmc
    - hdbscan
    - umap-learn
    - tttrlib  # [not win]
    - libcxx   # [osx]

app:
  entry: chisurf
  summary: ChiSurf analysis platform for fluorescence data

test:
  imports:
    - chisurf
  commands:
    - python -c "import chisurf, sys; print(getattr(chisurf, '__version__', 'ok'))"

about:
  home: https://github.com/Fluorescence-Tools/ChiSurf
  license: {{ data.get('license') }}
  license_file: LICENSE
  summary: |
    {{ data.get('description') }}
  description: |
    {{ data.get('description') }}

extra:
  recipe-maintainers:
    - tpeulen
