{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.get('name')|lower }}
  version: {{ data.get('version')|lower }}

source:
  path: ..

build:
  number: 0
  binary_relocation: True  # Relocate binaries correctly (for shared libraries, etc.).
  detect_binary_files_with_prefix: True  # [not win]
  entry_points:
    {% for entry_point_type, entry_points in data.get("entry_points", dict()).items() -%}
    {% for entry_point in entry_points -%}
    - {{ entry_point }}
    {% endfor %}
    {% endfor %}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake <4
    - ninja
    - make # [not win]
  host:
    - python
    - git
    - swig <4.3.0
    - numpy
    - pkg-config   # [not win]
    - llvm-openmp  # [osx]
    - libcxx  # [osx]
    - libgomp      # [linux]
    - typing-extensions 4.5.*
    - pytools 2024
    - pip
    - cython <3.0
    - pyyaml
    - numpy
    - pyqt           # Needed for pyrcc5 (updating PyQt resource files)
    # Needed for chinet
    - doxygen
    - boost-cpp
    # Needed to build tttrlib
    - hdf5
  run:
    - python =3.10
    - typing-extensions 4.5.*
    - pytools 2024
    - numpy
    - pyqt
    - pyyaml
    - click
    - click-didyoumean
    - pyqtgraph
    - matplotlib
    - scikit-image
    - deprecation
    - imp
    - pandas
    - scipy
    - numba
    - boost-cpp
    - mdtraj
    - ipython 7.33.*
    - notebook
    - emcee 3.1.*
    - pyopengl
    - pytables 3.9.*
    - pymol-open-source
    - guidata
    - guiqwt
    - python-docx
    - qtconsole 5.2.*
    - pyqtwebengine
    - libcxx  # [osx]
    - hmmlearn
    - sympy
    - zeus-mcmc

app:
  entry: chisurf
  summary: ChiSurf analysis platform for fluorescence data

test:
  imports:
    - chisurf
  commands:
    - chisurf &        # [linux or osx]

about:
  home: https://github.com/Fluorescence-Tools/ChiSurf
  license: {{ data.get('license') }}
  license_file: LICENSE
  summary: |
    {{ data.get('description') }}
  description: |
    {{ data.get('description') }}

extra:
  recipe-maintainers:
    - tpeulen
