{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.get('name')|lower }}
  version: {{ data.get('version')|lower }}

source:
  path: ..

build:
  number: 0
  string: np{{ CONDA_NPY }}py{{ CONDA_PY }}_{{ GIT_BUILD_STR }}
  entry_points:
    - chisurf=chisurf.__main__:main

requirements:
  host:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - pyyaml
    - setuptools
    - cython
  build:
    - python {{ python }}
    - setuptools
    - cython
    - {{ pin_compatible('numpy') }}
  run:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - cython
    - pyyaml
    - python-slugify
    - scipy
    - emcee
    - numba >=0.46.0
    - numexpr >=2.7.0
    - mdtraj
    - ipython 7.12.0.*
    - qtconsole 4.6.0.*
    - jupyter_client <6.0.0|>6.0.0
    - qtpy
    - pyqt >=5.13.1|<=5.12.1|>=5.9.0
    - qscintilla2 >=2.10.8
    - pyqtgraph >=0.10.0
    - matplotlib >=3.1.3
    - guiqwt >=3.0.3
    - pyopengl
    - python-docx
    - deprecation
    - pyopencl
    - progressbar2
    - mrcfile
    - htmd-pdb2pqr
    - pymol-open-source
    - opencv 3.4.1.*
    - labellib
    - tttrlib >=0.0.12
    - chinet >=0.0.3

about:
  home: https://github.com/Fluorescence-Tools/ChiSurf
  license: {{ data.get('license') }}
  license_file: LICENSE
  summary: |
    ChiSurf is an interactive global analysis software for time-resolved
    fluorescence data.
  description: |
    ChiSurf is an interactive analysis software for time-resolved
    fluorescence data.

extra:
  recipe-maintainers:
    - tpeulen
