{% set name = "chisurf" %}
#{% set version = "0.0.3" %}
{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: {{ name|lower }}
#  version: {{ version|lower }}
  version: {{ data.get('version')|lower }}

source:
  path: ..

build:
  number: 0
#  number: {{ GIT_DESCRIBE_NUMBER|int }}
#  string: np{{ CONDA_NPY }}py{{ CONDA_PY }}_{{ GIT_BUILD_STR }}
  entry_points:
    - chisurf=chisurf.__main__:main

requirements:
  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python=3.7.3
    - numpy
    - pyyaml
    - setuptools
    - cython
  run:
    - python=3.7.3
    - pyyaml
    - python-slugify
    - numpy
    - numba
    - scipy
    - emcee
    - numexpr
    - pytables
    - mdtraj
    - ipython
    - matplotlib
    - pyqt
    - pyqtgraph
    - qscintilla2
    - pyopengl
    - qtconsole
    - python-docx
    - labellib
    - deprecation
    - pyopencl
    - guiqwt
    - progressbar2
    - qtpy
    - mrcfile
    - htmd-pdb2pqr
    - pymol-open-source
    - opencv
    - labellib
    - tttrlib
    - chinet>=0.0.3
    - librttr
    - libmongoc

about:
  home: https://github.com/Fluorescence-Tools/ChiSurf
  license: GPL2.1
  license_file: LICENSE
  summary: |
    ChiSurf is an interactive global analysis software for time-resolved
    fluorescence data.
  description: |
    ChiSurf is an interactive analysis software for time-resolved
    fluorescence data.

extra:
  recipe-maintainers:
    - tpeulen
