{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.get('name')|lower }}
  version: {{ data.get('version')|lower }}

source:
  path: ..

build:
  number: 0
  string: np{{ CONDA_NPY }}py{{ CONDA_PY }}_{{ GIT_BUILD_STR }}
  entry_points:
    {% for entry_point_type, entry_points in data.get("entry_points", dict()).items() -%}
    {% for entry_point in entry_points -%}
    - {{ entry_point }}
    {% endfor %}
    {% endfor %}
requirements:
  host:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - typing_extensions
    - pyyaml
    - setuptools
    - cython
  build:
    - python {{ python }}
    - setuptools
    - typing_extensions
    - cython
    - pyyaml
    - {{ pin_compatible('numpy') }}
  run:
    - python {{ python }}
    - typing_extensions
    - pyyaml >=5.0
    - deprecation
    - progressbar2
    - imp >=2.12.0
    - python-slugify
    - {{ pin_compatible('numpy') }}
    - cython >=0.25.0
    - numexpr >=2.6.0
    - numba >=0.48.0
    - scipy >=1.4.0
    - emcee >=2.2.1
    - mdtraj >=1.9.0
    - ipython <=7.12.0
    - qtconsole <=4.6.0
    - jupyter_client <6.0.0|>6.0.0
    - matplotlib >=3.0.0
    - qtpy >=1.8.0
    - pyqt >=5.13.0|5.9.2.*|5.6.0.*
    - qscintilla2 >=2.9.3
    - pyqtgraph >=0.9.10
    - guiqwt >=3.0.0
    - pymol-open-source >=2.3.0
    - pyopengl
    - pyopencl
    - python-docx 0.8.10.*
    - htmd-pdb2pqr 0.0.2.*
    - opencv >=3.4.0
    - mrcfile >=1.1.2
    - labellib
    - tttrlib >=0.0.12
    - chinet >=0.0.5

about:
  home: https://github.com/Fluorescence-Tools/ChiSurf
  license: {{ data.get('license') }}
  license_file: LICENSE
  summary: |
    ChiSurf is an interactive global analysis software for time-resolved
    fluorescence data.
  description: |
    {{ data.get('description') }}

extra:
  recipe-maintainers:
    - tpeulen
