{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.get('name')|lower }}
  version: {{ data.get('version')|lower }}

source:
  path: ..

build:
  number: 0
  entry_points:
    {% for entry_point_type, entry_points in data.get("entry_points", dict()).items() -%}
    {% for entry_point in entry_points -%}
    - {{ entry_point }}
    {% endfor %}
    {% endfor %}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - setuptools
    - pyopencl
    - pocl  >=0.14      # [linux or osx]
    - oclgrind          # [win]
    - typing_extensions
    - cython
    - pyyaml
    - numpy
    # Needed for pyrcc5 (updated pyqt resource file)
    - pyqt
  host:
    - python
    - setuptools
    - cython
    - pyopencl
    - pocl  >=0.14      # [linux or osx]
    - oclgrind          # [win]
    - typing_extensions
    - pyyaml
    - numpy
    # Needed for pyrcc5 (updated pyqt resource file)
    - pyqt
  run:
    - python
    - numpy
    - pyyaml
    - qtpy
    - typing_extensions
    - matplotlib
    - scikit-fluorescence
    - deprecation
    - progressbar2
    - python-slugify
    - numexpr
    - numba
    - scipy <1.8
    - emcee
    - mdtraj
    - ipython
    - qtconsole
    - jupyter_client
    - pyqt
    - pyqtgraph
    - qscintilla2
    - guiqwt
    - guidata
    - pymol-open-source
    - pyopengl
    - pocl  >=0.14      # [linux or osx]
    - oclgrind          # [win]
    - python-docx
    - htmd-pdb2pqr
    - imp
    - chinet >=0.0.8
    - labellib
    - ndxplorer
    - clsmview
    - k2dist
    - tttrconvert

about:
  home: https://github.com/Fluorescence-Tools/ChiSurf
  license: {{ data.get('license') }}
  license_file: LICENSE
  summary: |
    {{ data.get('description') }}
  description: |
    {{ data.get('description') }}

extra:
  recipe-maintainers:
    - tpeulen
