{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.get('name')|lower }}
  version: {{ data.get('version')|lower }}

source:
  path: ..

build:
  number: 0
  string: np{{ CONDA_NPY }}py{{ CONDA_PY }}
  entry_points:
    {% for entry_point_type, entry_points in data.get("entry_points", dict()).items() -%}
    {% for entry_point in entry_points -%}
    - {{ entry_point }}
    {% endfor %}
    {% endfor %}
requirements:
  host:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - typing_extensions
    - pyyaml
    - setuptools
    - cython
  build:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - setuptools
    - typing_extensions
    - cython
    - pyyaml
    # Needed for pyrcc5 (updated pyqt resource file)
    - pyqt >=5.13.0|5.9.2.*|5.6.0.*
  run:
    # There is an issue in versions >= 3.7.3
    # https://www.riverbankcomputing.com/pipermail/pyqt/2019-August/042003.html
    # https://github.com/conda/conda-build/issues/2571
    - {{ pin_compatible('python', max_pin='3.7.3') }}
    - {{ pin_compatible('numpy') }}
    - pyyaml >=5.0.0
    - qtpy >=1.8.0
    - pyqt >=5.13.0|5.9.2.*|5.6.0.*
    - pyqtgraph >0.10.0|0.9.10
    - typing_extensions
    - matplotlib >=3.0.0
    - scikit-fluorescence >=0.0.1
    - deprecation
    - progressbar2
    - python-slugify
    - cython >=0.25.0
    - numexpr >=2.6.0
    - numba >=0.48.0
    - scipy >=1.4.0
    - emcee >=3.0.0
    - mdtraj >=1.9.0
    - ipython <=7.12.0
    - qtconsole <=4.6.0
    - jupyter_client 5.3.4.*
    - qscintilla2 >=2.9.3
    - guiqwt >=3.0.3
    - guidata >=1.7.8
    - pymol-open-source >=2.3.0
    - pyopengl
    - pyopencl
    - python-docx 0.8.10.*
    - htmd-pdb2pqr 0.0.2.*
    - opencv >=3.4.0
    - mrcfile >=1.1.2
    - chinet >=0.0.5

about:
  home: https://github.com/Fluorescence-Tools/ChiSurf
  license: {{ data.get('license') }}
  license_file: LICENSE
  summary:
    {{ data.get('description') }}
  description: |
    {{ data.get('description') }}

extra:
  recipe-maintainers:
    - tpeulen
