[project]
name = "chinet"
version = "0.3.0"
requires-python = ">=3.10"
description = "Pure-Python graph and parameter runtime for ChiSurf."
readme = "README.md"
authors = [
    {name = "Thomas-Otavio Peulen", email = "thomas.otavio.peulen@gmail.com"},
]
license = "MIT"
license-files = ["LICENSE.txt"]

dependencies = [
    "numpy",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["chinet*"]
