"""Operation-parameter schema: load, seed, query, validate (PRD-11).

The data-side analog of chinet's typed node ports. ``mfdb_operation_parameter_def``
(declared in ``mfdb_flr_ext.dic``, generated by ``reconcile_schema``) holds the typed
parameter schema per operation type; the authored source for its rows is
``data/operation_parameter_defs.json`` (consistent with the other authored seeds read
by ``vocabulary_loader``). Validation rejects unknown parameters and missing required
ones so operation parameters are typed, described, and checked rather than a free bag.
"""

from __future__ import annotations

import json
import logging
import sqlite3
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping

logger = logging.getLogger(__name__)

_DEFS_PATH = Path(__file__).parent.parent / "data" / "operation_parameter_defs.json"


@dataclass(frozen=True)
class OperationParameterDef:
    """One typed parameter declaration for an operation type."""

    operation_type: str
    name: str
    value_type: str
    units: str | None = None
    default_value: str | None = None
    lower_bound: float | None = None
    upper_bound: float | None = None
    required: bool = False
    repeatable: bool = False
    role_domain: str | None = None
    description: str | None = None


class OperationParameterError(ValueError):
    """A parameter set violates the operation type's declared schema."""


def load_operation_parameter_defs() -> list[OperationParameterDef]:
    """Load the authored operation-parameter definitions (single source)."""
    data = json.loads(_DEFS_PATH.read_text(encoding="utf-8"))
    defs: list[OperationParameterDef] = []
    for op_type, params in data.items():
        if op_type.startswith("_"):
            continue
        for p in params:
            defs.append(OperationParameterDef(operation_type=op_type, **p))
    return defs


def bootstrap_operation_parameter_defs(conn: sqlite3.Connection) -> None:
    """Seed ``mfdb_operation_parameter_def`` from the authored source (idempotent).

    Replaces the authored rows for each declared operation type so the table always
    reflects the current authored source. ``def_id`` is assigned explicitly because
    the dictionary-generated key column is not a rowid alias.
    """
    defs = load_operation_parameter_defs()
    op_types = sorted({d.operation_type for d in defs})
    try:
        with conn:
            for op_type in op_types:
                conn.execute(
                    "DELETE FROM mfdb_operation_parameter_def WHERE operation_type = ?",
                    (op_type,),
                )
            next_id = (
                conn.execute(
                    "SELECT COALESCE(MAX(def_id), 0) FROM mfdb_operation_parameter_def"
                ).fetchone()[0]
                + 1
            )
            for d in defs:
                conn.execute(
                    """INSERT INTO mfdb_operation_parameter_def
                       (def_id, operation_type, name, value_type, units, default_value,
                        lower_bound, upper_bound, required, repeatable, role_domain,
                        description)
                       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                    (
                        next_id, d.operation_type, d.name, d.value_type, d.units,
                        d.default_value, d.lower_bound, d.upper_bound,
                        int(d.required), int(d.repeatable), d.role_domain,
                        d.description,
                    ),
                )
                next_id += 1
    except sqlite3.OperationalError:
        # Table not present yet (best-effort during early migration).
        logger.debug("mfdb_operation_parameter_def not available; skipped seeding")


def get_operation_parameter_defs(
    conn: sqlite3.Connection, operation_type: str
) -> dict[str, OperationParameterDef]:
    """Return ``{name: OperationParameterDef}`` for an operation type from the DB."""
    try:
        rows = conn.execute(
            """SELECT operation_type, name, value_type, units, default_value,
                      lower_bound, upper_bound, required, repeatable, role_domain,
                      description
               FROM mfdb_operation_parameter_def
               WHERE operation_type = ? AND deleted_at IS NULL""",
            (operation_type,),
        ).fetchall()
    except sqlite3.OperationalError:
        return {}
    out: dict[str, OperationParameterDef] = {}
    for r in rows:
        out[r[1]] = OperationParameterDef(
            operation_type=r[0], name=r[1], value_type=r[2], units=r[3],
            default_value=r[4], lower_bound=r[5], upper_bound=r[6],
            required=bool(r[7]), repeatable=bool(r[8]), role_domain=r[9],
            description=r[10],
        )
    return out


def _check_param_value(name: str, value: Any, d: OperationParameterDef) -> str | None:
    """Return an error message if ``value`` violates the param def, else ``None``.

    Checks the declared ``value_type`` (shared with the dictionary boundary
    validator) and the numeric ``lower_bound``/``upper_bound`` (PRD-11). A value may
    be a scalar, a list/tuple (repeatable, role-indexed), or a rich mapping carrying
    ``value``/``error``/``fixed``/``bounds``/``units`` — the inner ``value`` is the
    one checked.
    """
    from mfdb.security.boundary_validation import check_value_type

    if isinstance(value, (list, tuple)):
        for i, element in enumerate(value):
            err = _check_param_value(f"{name}[{i}]", element, d)
            if err:
                return err
        return None
    if isinstance(value, Mapping) and "value" in value:
        value = value["value"]
    type_error = check_value_type(value, d.value_type, field_name=name)
    if type_error:
        return type_error
    if value is None or (d.lower_bound is None and d.upper_bound is None):
        return None
    try:
        numeric = float(value)
    except (TypeError, ValueError):
        return None  # non-numeric type already validated above
    if d.lower_bound is not None and numeric < d.lower_bound:
        return f"{name}: {value!r} below lower bound {d.lower_bound}"
    if d.upper_bound is not None and numeric > d.upper_bound:
        return f"{name}: {value!r} above upper bound {d.upper_bound}"
    return None


def validate_operation_parameters(
    conn: sqlite3.Connection,
    operation_type: str,
    parameters: Mapping[str, Any] | None,
) -> None:
    """Validate a parameter mapping against an operation type's declared schema.

    Rejects unknown parameter names, missing required ones, type-incoherent values,
    and out-of-bounds values. No-op when the operation type has no declared schema
    (unvalidated, backward compatible). Raises :class:`OperationParameterError` on a
    violation.
    """
    defs = get_operation_parameter_defs(conn, operation_type)
    if not defs:
        return
    provided = dict(parameters or {})
    unknown = sorted(set(provided) - set(defs))
    if unknown:
        raise OperationParameterError(
            f"Unknown parameter(s) {unknown} for operation_type {operation_type!r}; "
            f"declared: {sorted(defs)}"
        )
    missing = sorted(n for n, d in defs.items() if d.required and n not in provided)
    if missing:
        raise OperationParameterError(
            f"Missing required parameter(s) {missing} for operation_type "
            f"{operation_type!r}"
        )
    errors = [
        err
        for name, value in provided.items()
        if (err := _check_param_value(name, value, defs[name])) is not None
    ]
    if errors:
        raise OperationParameterError(
            f"Invalid parameter value(s) for operation_type {operation_type!r}: "
            + "; ".join(errors)
        )
