
name: Build and Upload Conda Packages

on:
  workflow_dispatch:
#  push:
#    branches:
#      - develop
  release:
    types: ['released', 'prereleased']

jobs:
  build:
    name: CondaBuild (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.10"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: "Set SDK on MacOS (if needed)"
        if: startsWith(matrix.os, 'macos')
        run: build_tools/install_macos_sdk.sh

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          miniforge-version: latest
          channels: conda-forge,bioconda,tpeulen,defaults
          channel-priority: true

      - name: Display Conda Settings
        shell: bash -el {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort

      - name: Build and Upload Conda Package
        uses: aganders3/headless-gui@v1
        with:
          shell: bash -el {0}
          run: |
            # Check if RUNNER_OS is macOS and set CONDA_SUBDIR accordingly
            if [[ "$RUNNER_OS" == "macos" ]]; then export CONDA_SUBDIR=osx-amd64; fi
      
            # Create and activate the build environment
            echo "Creating build environment..."
            conda create -y -n build-env python=${{ matrix.python-version }}
            conda activate build-env
      
            # Install necessary build tools
            conda install -y mamba conda-build boa anaconda-client
      
            # Change to the conda-recipe directory and build the package
            cd conda-recipe
            conda mambabuild . --output-folder conda-bld
      
            # Upload the built package to Anaconda Cloud
            if command -v anaconda &> /dev/null; then
              anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u tpeulen --force conda-bld/**/*.tar.bz2
            else
              echo "anaconda-client not found, skipping upload."
              exit 1
            fi
