
name: Build and Upload Conda Packages

on:
  workflow_dispatch:
  push:
    branches:
      - development
  release:
    types: ['released', 'prereleased']
  schedule:
    # Every Monday at 11PM UTC
    - cron: "0 11 * * 1"

jobs:
  build:
    name: CondaBuild (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]#, "macos-latest"] #, "windows-latest"]
        python-version: ["3.10"]
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Checkout Repository (with all submodules)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0           # full history, not just the latest commit
          submodules: recursive    # initialize & update all nested submodules

      - name: "Set SDK on MacOS (if needed)"
        if: startsWith(matrix.os, 'macos')
        run: build_tools/install_macos_sdk.sh

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          conda-remove-defaults: "true"
          channels: conda-forge,bioconda
          channel-priority: strict

      - name: Display Conda Settings
        shell: bash -el {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort

      # https://raw.githubusercontent.com/conda-forge/conda-forge-pinning-feedstock/master/recipe/conda_build_config.yaml \
      - name: Download conda_build_config.yaml
        shell: bash
        run: |
          echo "Fetching conda-forge’s pinning config…"
          curl -sSL \
            https://raw.githubusercontent.com/conda-forge/conda-forge-pinning-feedstock/a3466e9340d2de032119f8fa1a9a4f5d57c456d3/recipe/conda_build_config.yaml \
            -o conda_build_config.yaml
          echo "Pinning config version:"
          head -n 5 conda_build_config.yaml

      - name: Build and Upload Conda Package
        uses: aganders3/headless-gui@v1
        with:
          shell: bash -el {0}
          run: |
            conda install mamba conda-build boa anaconda-client

            cd conda-recipe

            conda mambabuild . \
              --variant-config-files ../conda_build_config \
              --output-folder conda-bld
      
            anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u tpeulen --force conda-bld/**/*.tar.bz2
