name: Conda Build

on:
  workflow_dispatch:
  push:
    branches:
      - development
  release:
    types: ['released', 'prereleased']
  schedule:
    # Every Monday at 11PM UTC
    - cron: "0 23 * * 1"

jobs:
  build:
    name: CondaBuild (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest"] # "ubuntu-latest"] #, "macos-latest"] #,
    steps:
      - uses: conda-incubator/setup-miniconda@v3
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Download conda_build_config.yaml
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          echo "Fetching conda-forge’s pinning config…"
          curl -sSL \
            https://raw.githubusercontent.com/conda-forge/conda-forge-pinning-feedstock/master/recipe/conda_build_config.yaml \
            -o conda_build_config.yaml
          echo "Pinning config version:"
          head -n 5 conda_build_config.yaml

      - name: Download conda_build_config.yaml (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          Write-Host "Fetching conda-forge’s pinning config…"
          Invoke-WebRequest `
            -Uri 'https://raw.githubusercontent.com/conda-forge/conda-forge-pinning-feedstock/master/recipe/conda_build_config.yaml' `
            -OutFile conda_build_config.yaml -UseBasicParsing
          Write-Host "Pinning config version:"
          Get-Content conda_build_config.yaml -TotalCount 5

      - name: "Set SDK on MacOS (if needed)"
        if: startsWith(matrix.os, 'macos')
        run: build_tools/install_macos_sdk.sh

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          conda-remove-defaults: true
          miniforge-version: latest
          channels: conda-forge,bioconda
          channel-priority: true
          activate-environment: benv

      - name: Display Conda Settings
        shell: bash -el {0}
        run: |
          conda info

      - name: Build + Upload Conda Package
        shell: bash -el {0}
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          mamba install -n benv -y boa conda-build anaconda-client
          mamba run -n benv conda mambabuild conda-recipe