name: Conda Build

on:
  workflow_dispatch:
  push:
    branches:
      - development
  release:
    types: ['released', 'prereleased']
  schedule:
    # Every Monday at 11PM UTC
    - cron: "0 23 * * 1"

jobs:
  build:
    name: CondaBuild (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"] #, "windows-latest"] , "macos-latest"] #,
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download conda_build_config.yaml
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          echo "Fetching conda-forge’s pinning config…"
          curl -sSL \
            https://raw.githubusercontent.com/conda-forge/conda-forge-pinning-feedstock/master/recipe/conda_build_config.yaml \
            -o conda_build_config.yaml
          echo "Pinning config version:"
          head -n 5 conda_build_config.yaml

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          conda-remove-defaults: true
          miniforge-version: latest
          channels: conda-forge,bioconda
          channel-priority: true
          activate-environment: benv

      - name: Display Conda Settings
        shell: bash -el {0}
        run: |
          conda info

      - name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@v2.0.0
        with:
          meta_yaml_dir: conda-recipe # Replace with the path to your meta.yaml directory
          user: tpeulen # Replace with your Anaconda username (or an Anaconda organization username)
          token: ${{ secrets.ANACONDA_TOKEN }} # Replace with the name of your Anaconda Token secret
