name: Conda Build

on:
  workflow_dispatch:
  push:
    branches:
      - development
  release:
    types: ['released', 'prereleased']
  schedule:
    # Every Monday at 11PM UTC
    - cron: "0 11 * * 1"

jobs:
  build:
    name: CondaBuild (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"] # "macos-latest"] #,
        python-version: ["3.10"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: "Set SDK on MacOS (if needed)"
        if: startsWith(matrix.os, 'macos')
        run: build_tools/install_macos_sdk.sh

      - name: Install Visual Studio 2017 (Windows only)
        if: matrix.os == 'windows-latest'
        run: |
          choco install visualstudio2017buildtools --version=15.9.54 -y
          choco install visualstudio2017-workload-vctools -y
          setx PATH "%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build"

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          miniforge-version: latest
          channels: conda-forge,bioconda,tpeulen
          channel-priority: true

      - name: Display Conda Settings
        shell: bash -el {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort

      - name: Build Conda Package
        uses: aganders3/headless-gui@v1
        with:
          shell: bash -el {0}
          run: |
            conda install mamba conda-build boa anaconda-client
            conda mambabuild conda-recipe
